function g(b){return function(){return b}}
(function(){function b(a){try{if(navigator.plugins&&navigator.plugins.length)for(var b=0;b<navigator.plugins.length;b++){var c=navigator.plugins[b];if(0<=c.name.indexOf(a))return c.name+(c.description?"|"+c.description:"")}}catch(d){}return""}function a(a){var r=new Date,z=new Date,v=[g("TF1"),g("020"),function(){return ScriptEngineMajorVersion()},function(){return ScriptEngineMinorVersion()},function(){return ScriptEngineBuildVersion()},function(){return e("{7790769C-0471-11D2-AF11-00C04FA35D02}")},function(){return e("{89820200-ECBD-11CF-8B85-00AA005B4340}")},
function(){return e("{283807B5-2C60-11D0-A31D-00AA00B92C03}")},function(){return e("{4F216970-C90C-11D1-B5C7-0000F8051515}")},function(){return e("{44BBA848-CC51-11CF-AAFA-00AA00B6015C}")},function(){return e("{9381D8F2-0288-11D0-9501-00AA00B911A5}")},function(){return e("{4F216970-C90C-11D1-B5C7-0000F8051515}")},function(){return e("{5A8D6EE0-3E18-11D0-821E-444553540000}")},function(){return e("{89820200-ECBD-11CF-8B85-00AA005B4383}")},function(){return e("{08B0E5C0-4FCB-11CF-AAA5-00401C608555}")},
function(){return e("{45EA75A0-A269-11D1-B5BF-0000F8051515}")},function(){return e("{DE5AED00-A4BF-11D1-9948-00C04F98BBC9}")},function(){return e("{22D6F312-B0F6-11D0-94AB-0080C74C7E95}")},function(){return e("{44BBA842-CC51-11CF-AAFA-00AA00B6015B}")},function(){return e("{3AF36230-A269-11D1-B5BF-0000F8051515}")},function(){return e("{44BBA840-CC51-11CF-AAFA-00AA00B6015C}")},function(){return e("{CC2A9BA0-3BDD-11D0-821E-444553540000}")},function(){return e("{08B0E5C0-4FCB-11CF-AAA5-00401C608500}")},
function(){return eval("navigator.appCodeName")},function(){return eval("navigator.appName")},function(){return eval("navigator.appVersion")},function(){return l(["navigator.productSub","navigator.appMinorVersion"])},function(){return eval("navigator.browserLanguage")},function(){return eval("navigator.cookieEnabled")},function(){return l(["navigator.oscpu","navigator.cpuClass"])},function(){return eval("navigator.onLine")},function(){return eval("navigator.platform")},function(){return eval("navigator.systemLanguage")},
function(){return eval("navigator.userAgent")},function(){return l(["navigator.language","navigator.userLanguage"])},function(){return eval("document.defaultCharset")},function(){return eval("document.domain")},function(){return eval("screen.deviceXDPI")},function(){return eval("screen.deviceYDPI")},function(){return eval("screen.fontSmoothingEnabled")},function(){return eval("screen.updateInterval")},function(){return 0!==Math.abs(p-q)},function(){return d(r)},g("@UTC@"),function(){var a=0,a=0;d(r)&&
(a=Math.abs(p-q));return-(r.getTimezoneOffset()+a)/60},function(){return(new Date(2005,5,7,21,33,44,888)).toLocaleString()},function(){return eval("screen.width")},function(){return eval("screen.height")},function(){return m.Acrobat},function(){return m.Flash},function(){return m.QuickTime},function(){return m["Java Plug-in"]},function(){return m.Director},function(){return m.Office},g("@CT@"),function(){return p},function(){return q},function(){return r.toLocaleString()},function(){return eval("screen.colorDepth")},
function(){return eval("window.screen.availWidth")},function(){return eval("window.screen.availHeight")},function(){return eval("window.screen.availLeft")},function(){return eval("window.screen.availTop")},function(){return b("Acrobat")},function(){return b("Adobe SVG")},function(){return b("Authorware")},function(){return b("Citrix ICA")},function(){return b("Director")},function(){return b("Flash")},function(){return b("MapGuide")},function(){return b("MetaStream")},function(){return b("PDFViewer")},
function(){return b("QuickTime")},function(){return b("RealOne")},function(){return b("RealPlayer Enterprise")},function(){return b("RealPlayer Plugin")},function(){return b("Seagate Software Report")},function(){return b("Silverlight")},function(){return b("Windows Media")},function(){return b("iPIX")},function(){return b("nppdf.so")},function(){var a=document.createElement("span");a.innerHTML="&nbsp;";a.style.position="absolute";a.style.left="-9999px";document.body.appendChild(a);var b=a.offsetHeight;
document.body.removeChild(a);return b},g(""),g(""),g(""),g(""),g(""),g(""),g(""),g(""),g(""),g(""),g(""),g(""),g(""),g(""),g("5.6.0-0"),g("")];h();for(var f="",k=0;k<v.length;k++){a&&(f+=c(v[k].toString(),'"',"'",!0),f+="=");var s;try{s=v[k](this)}catch(B){s=""}f+=a?s:escape(s);f+=";";a&&(f+="\\n")}f=c(f,escape("@UTC@"),(new Date).getTime());f=c(f,escape("@CT@"),(new Date).getTime()-z.getTime());return window.f1b5?window.f1b5(f):f}function c(a,b,c,d){"boolean"!==typeof d&&(d=!1);for(var f=!0,k;0<=
(k=a.indexOf(b))&&(d||f);)a=a.substr(0,k)+c+a.substr(k+b.length),f=!1;return a}function d(a){var b=Math.min(p,q);return 0!==Math.abs(p-q)&&a.getTimezoneOffset()===b}function h(){for(var a="Acrobat;Flash;QuickTime;Java Plug-in;Director;Office".split(";"),b=0;b<a.length;b++){var c=a[b],d=m,f=c,k=c,c="";try{if(navigator.plugins&&navigator.plugins.length)for(var h=RegExp(k+".* ([0-9._]+)"),k=0;k<navigator.plugins.length;k++){var e=h.exec(navigator.plugins[k].name);null===e&&(e=h.exec(navigator.plugins[k].description));
e&&(c=e[1])}else if(window.ActiveXObject&&w[k])try{var l=new ActiveXObject(w[k][0]),c=w[k][1](l)}catch(n){c=""}}catch(p){c=p.message}d[f]=c}}function l(a){for(var b=0;b<a.length;b++)try{var c=eval(a[b]);if(c)return c}catch(d){}return""}function e(a){var b="";try{"undefined"!==typeof n.a.getComponentVersion&&(b=n.a.getComponentVersion(a,"ComponentID"))}catch(c){a=c.message.length,b=escape(c.message.substr(0,40<a?40:a))}return b}function A(a){function b(a){d=d<<a[0]|a[1];for(f+=a[0];6<=f;)a=d>>f-6&
63,c+=t.substring(a,a+1),f-=6,d^=a<<f}var c="",d=0,f=0;b([6,(a.length&7)<<3|0]);b([6,a.length&56|1]);for(var e=0;e<a.length;e++){if(void 0==x[a.charCodeAt(e)])return;b(x[a.charCodeAt(e)])}b(x[0]);0<f&&b([6-f,0]);return c}var n={},p=(new Date(2005,0,15)).getTimezoneOffset(),q=(new Date(2005,6,15)).getTimezoneOffset(),m=[],w={Flash:["ShockwaveFlash.ShockwaveFlash",function(a){return a.getVariable("$version")}],Director:["SWCtl.SWCtl",function(a){return a.ShockwaveVersion("")}]};try{n.a=document.createElement("span"),
"undefined"!==typeof n.a.addBehavior&&n.a.addBehavior("#default#clientCaps")}catch(C){}var m={},x={1:[4,15],110:[8,239],74:[8,238],57:[7,118],56:[7,117],71:[8,233],25:[8,232],101:[5,28],104:[7,111],4:[7,110],105:[6,54],5:[7,107],109:[7,106],103:[9,423],82:[9,422],26:[8,210],6:[7,104],46:[6,51],97:[6,50],111:[6,49],7:[7,97],45:[7,96],59:[5,23],15:[7,91],11:[8,181],72:[8,180],27:[8,179],28:[8,178],16:[7,88],88:[10,703],113:[11,1405],89:[12,2809],107:[13,5617],90:[14,11233],42:[15,22465],64:[16,44929],
0:[16,44928],81:[9,350],29:[8,174],118:[8,173],30:[8,172],98:[8,171],12:[8,170],99:[7,84],117:[6,41],112:[6,40],102:[9,319],68:[9,318],31:[8,158],100:[7,78],84:[6,38],55:[6,37],17:[7,73],8:[7,72],9:[7,71],77:[7,70],18:[7,69],65:[7,68],48:[6,33],116:[6,32],10:[7,63],121:[8,125],78:[8,124],80:[7,61],69:[7,60],119:[7,59],13:[8,117],79:[8,116],19:[7,57],67:[7,56],114:[6,27],83:[6,26],115:[6,25],14:[6,24],122:[8,95],95:[8,94],76:[7,46],24:[7,45],37:[7,44],50:[5,10],51:[5,9],108:[6,17],22:[7,33],120:[8,
65],66:[8,64],21:[7,31],106:[7,30],47:[6,14],53:[5,6],49:[5,5],86:[8,39],85:[8,38],23:[7,18],75:[7,17],20:[7,16],2:[5,3],73:[8,23],43:[9,45],87:[9,44],70:[7,10],3:[6,4],52:[5,1],54:[5,0]},y="%20 ;;; %3B %2C und fin ed; %28 %29 %3A /53 ike Web 0; .0 e; on il ck 01 in Mo fa 00 32 la .1 ri it %u le".split(" "),t=".0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz";window.f1b5=function(a){for(var b=a,c=0;y[c];c++)b=b.split(y[c]).join(String.fromCharCode(c+1));b=A(b);if(void 0==b)return a;
for(var c=65535,d=0;d<a.length;d++)c=(c>>>8|c<<8)&65535,c^=a.charCodeAt(d)&255,c^=(c&255)>>4,c^=c<<12&65535,c^=(c&255)<<5&65535;c&=65535;a=""+t.charAt(c>>>12);a+=t.charAt(c>>>6&63);a+=t.charAt(c&63);return b+a};n.collect=function(c){try{if(!c)return a();var b;a:{var d;try{d=document.getElementById(c)}catch(e){}if(null===d||"undefined"===typeof d)try{d=document.getElementsByName(c)[0]}catch(f){}if(null===d||"undefined"===typeof d)for(var h=0;h<document.forms.length;h++)for(var l=document.forms[h],
m=0;m<l.elements.length;m++){var n=l[m];if(n.name===c||n.id===c){b=n;break a}}b=d}if(null!==b)try{b.value=a()}catch(p){b.value=escape(p.message)}}catch(q){}};window.fortyone=n;var u=navigator.userAgent.toLowerCase();"Gecko"===navigator.product&&2>=parseInt(u.substring(u.indexOf("rv:")+3,u.indexOf(")",u.indexOf("rv:")+3)).split(".")[0])&&window.fortyone.collect()})();var microadCompass=microadCompass||{};microadCompass.cookieEnabled=!1;microadCompass.environment="production";
microadCompass.legacyIE=!1;var microad=microad||{};microad.advertising=microad.advertising||{};microad.advertising.ssp=microad.advertising.ssp||{};
/msie [6-8]/i.test(window.navigator.userAgent)&&(microadCompass.legacyIE=!0,Array.prototype.indexOf||(Array.prototype.indexOf=function(b){if(null==this)throw new TypeError;var a=Object(this),c=a.length>>>0;if(0===c)return-1;var d=0;0<arguments.length&&(d=Number(arguments[1]),d!=d?d=0:0!=d&&Infinity!=d&&-Infinity!=d&&(d=(0<d||-1)*Math.floor(Math.abs(d))));if(d>=c)return-1;for(d=0<=d?d:Math.max(c-Math.abs(d),0);d<c;d++)if(d in a&&a[d]===b)return d;return-1}));
microadCompass.Object=microadCompass.Object||{create:function(b){function a(){}if(Object.create)return Object.create(b);if(1!==arguments.length)throw Error("[MicroAd COMPASS] Object.create implementation only accepts one parameter.");a.prototype=b;return new a}};
microadCompass.AdInitializer=microadCompass.AdInitializer||function(){function b(){return a?a:a=this}var a;b.prototype.isAlreadyInitialized=!1;b.prototype.initialize=function(c){this.isAlreadyInitialized||(this._settings=new microadCompass.Settings(c?c:microadCompass.environment),microadCompass.environment=this._settings.env,this.logger=new microadCompass.Logger(this._settings),window.addEventListener&&window.addEventListener("error",function(c){c={m:c.message?c.message:""};/microad compass/i.test(c.m)&&
a.logger.send(c)},!1),(new microadCompass.Cookie(this._settings)).beginGetCookieEnabledFlag(this._callback),this.isAlreadyInitialized=!0)};b.prototype._callback=function(c){var b=microadCompass.queue,h=microadCompass.Flash.isEnabled(),l=microadCompass.Flash.getVersion(),e=new microadCompass.QueueProcessor(a._settings,b,c,h,l);e.appendHook();e.processBulkQueue();window.addEventListener?window.addEventListener("load",function(){e.removeHook()}):window.attachEvent&&window.attachEvent("onload",function(){e.removeHook()})};
return b}();
microadCompass.AdRequestor=microadCompass.AdRequestor||function(){function b(a){this._settings=a}b.USE_ADTRUTH_RATIO=100;b.prototype.sendRequest=function(a,c,d,h){var l=this._settings.serverUrl;a=this._createRequestParams(a,c,d,h);c=this.getUseAdTruth(navigator.userAgent,b.USE_ADTRUTH_RATIO);l=this.createRequestURL(l,a,c);this._sendRequestByJSONP(l)};b.prototype._createRequestParams=function(a,c,b,h){return{spot:a.spot,cookie:c?"1":"0",flash:b?"1":"0",flashver:h?h.toString():"",cb:"microadCompass.AdRequestor.callback",url:a.url?
a.url.replace("${COMPASS_EXT_URL}",location.href):"",referrer:a.referrer?a.referrer.replace("${COMPASS_EXT_REF}",document.referrer):"",ifa:a.ifa?a.ifa.replace("${COMPASS_EXT_IFA}",""):"",appId:a.appid?a.appid.replace("${COMPASS_EXT_APPID}",""):"",geo:a.geo?a.geo.replace("${COMPASS_EXT_GEO}",""):""}};b.prototype.getUseAdTruth=function(a,c){return/(iphone|ipad|ipod|android|windows phone)/i.test(a)?Math.floor(100*Math.random())<=c:!1};b.prototype.createRequestURL=function(a,c,b){a=a+"?spot="+encodeURIComponent(c.spot)+
"&cookie="+c.cookie+"&flash="+c.flash+"&cb="+c.cb;c.flash&&(a+="&flashver="+encodeURIComponent(c.flashver));a+="&url="+encodeURIComponent(c.url);a+="&referrer="+encodeURIComponent(c.referrer);c.ifa&&(a+="&ifa="+c.ifa);c.appId&&(a+="&appid="+c.appId);c.geo&&/^[0-9\.\-]+,[0-9\.\-]+$/.test(c.geo)&&(a+="&geo="+c.geo);b&&"undefined"!==typeof fortyone&&(a+="&payload="+encodeURIComponent(fortyone.collect()));return a};b.prototype._sendRequestByJSONP=function(a){var c=document.getElementsByTagName("script")[0],
b=document.createElement("script");b.type="text/javascript";b.charset="UTF-8";b.async=!0;b.defer=!0;c.parentNode.insertBefore(b,c);b.src=a;return b};b.callback=function(a){if(!b.validateResponse(a))throw Error("[MicroAd COMPASS callback] Invalid response.");(new microadCompass.AdDisplayController(a)).beginDisplayAd()};b.validateResponse=function(a){return a&&a.hasOwnProperty("spot")};return b}();var console=console||{log:function(){}};
microadCompass.Logger=microadCompass.Logger||function(){function b(a,b){this._settings=a;this._prefix=b?b:""}b.LOGGING_PERCENTAGE=10;b.log=function(a,b){"undefined"!==typeof console&&(console.log(a),b&&console.trace())};b.prototype.log=function(a,c){b.log("["+this._prefix+"] "+a,c)};b.prototype.send=function(a){if(!(Math.floor(100*Math.random())>=b.LOGGING_PERCENTAGE)){var c=[],d;for(d in a)"undefined"!==typeof a[d]&&c.push(d+"="+encodeURIComponent(a[d]));(new Image).src=this._settings.debugUrl+"?"+
c.join("&")}};return b}();microadCompass.AdDisplayController=microadCompass.AdDisplayController||function(){function b(a){var b=this._getSpotDivElement(a.spot);this._creative=microadCompass.CreativeFactory.getInstance(a,b)}b.prototype._getSpotDivElement=function(a){return document.getElementById(a)};b.prototype.beginDisplayAd=function(){this._creative.initialize();this._creative.display()};return b}();
microadCompass.Creative=microadCompass.Creative||{platform:{pc:"1",smartphone:"2"},display:{overlay:"overlay",inline:"inline",interstitial:"interstitial"}};
microadCompass.CreativeFactory=microadCompass.CreativeFactory||function(){function b(){throw new ReferenceError("[MicroAd COMPASS] Do not construct this object");}b.getInstance=function(a,b){return a.display&&a.display.toLowerCase()===microadCompass.Creative.display.overlay?new microadCompass.OverlayCreative(a,b):new microadCompass.IframeCreative(a,b)};return b}();
microadCompass.IframeCreative=microadCompass.IframeCreative||function(){function b(a,b){this._adWidth=a.width?a.width:"";this._adHeight=a.height?a.height:"";this._platform=a.platform?a.platform:"";this._adTag=a.adtag?a.adtag:"";this._impTag=a.imptag?a.imptag:"";this._syncTag=a.synctag?a.synctag:"";this._spotWidth=a.spotwidth?a.spotwidth:"";this._spotHeight=a.spotheight?a.spotheight:"";this._display=a.display?a.display:"";this._spotDivElement=b;this._isNeededBeacon=!0;this.ssp=new microadCompass.SSP}
b.prototype.initialize=function(){this._adTag&&(microadCompass.legacyIE||(this._calculateSpotDivElementSize(),this._spotDivElement.style.display="-webkit-box",this._spotDivElement.style.WebkitBoxAlign="center",this._spotDivElement.style.WebkitBoxPack="center",/firefox/i.test(navigator.userAgent)&&(this._spotDivElement.style.width="100%",this._display===microadCompass.Creative.display.inline?this._spotDivElement.style.textAlign="center":(this._spotDivElement.style.display="-moz-box",this._spotDivElement.style.MozBoxAlign=
"center",this._spotDivElement.style.MozBoxPack="center"))),this._iframe=document.createElement("iframe"),this._iframe.setAttribute("scrolling","no"),this._iframe.setAttribute("marginwidth","0"),this._iframe.setAttribute("marginheight","0"),this._iframe.setAttribute("allowFullScreen","true"),this._iframe.setAttribute("allowTransparency","true"),this._iframe.setAttribute("border","0"),this._iframe.setAttribute("frameBorder","0"),this._iframe.style.border="0",this._spotDivElement.appendChild(this._iframe))};
b.prototype._getAltBannerName=function(a,b){var d=a+"-"+b;return 0<=this.ssp.compass.altBanners.indexOf(d)?d+".gif":null};b.prototype._getSpotWidth=function(){var a=screen.width>screen.height?screen.height:screen.width;/linux; u;/i.test(navigator.userAgent)&&/android 4/i.test(navigator.userAgent)&&(a/=window.devicePixelRatio);320>a&&(a=320);return a};b.prototype._calculateIframeSize=function(){this._iframe.width="0"===this._adWidth?this._getSpotWidth()+"px":this._adWidth+"px";this._iframe.height=
this._adHeight+"px"};b.prototype._calculateSpotDivElementSize=function(){if(this._platform===microadCompass.Creative.platform.smartphone)if(this._display!==microadCompass.Creative.display.inline)this._spotDivElement.style.width="",this._spotDivElement.style.height="";else{var a=this._spotDivElement.style.width.replace("px",""),b=this._spotDivElement.style.height.replace("px","");if(0<this._spotWidth||0<a)a=0<this._spotWidth?this._spotWidth:a,"0"===this._adWidth?this._spotDivElement.style.width=this._getSpotWidth()+
"px":0<this._adWidth&&a>=this._adWidth?this._spotDivElement.style.width=a+"px":a<this._adWidth&&(this._spotDivElement.style.width=this._adWidth+"px");if(0<this._spotHeight||0<b)b=0<this._spotHeight?this._spotHeight:b,b>=this._adHeight?this._spotDivElement.style.height=this._spotHeight+"px":b<this._adHeight&&(this._spotDivElement.style.height=this._adHeight+"px")}};b.prototype._getIframeDocument=function(a){this._calculateIframeSize();var b=parseInt(this._iframe.width),d="";if(microadCompass.legacyIE||
/msie 9/i.test(a)){a=this._iframe.contentWindow.document;if(0<=this._adTag.indexOf("adingoFluct.showAd"))d=this.ssp.fluct.convertAdCodeLessThanIE9(this._adTag);else if(/<scr[ ]*ipt/i.test(this._adTag)){b=this._getAltBannerName(this._adWidth,this._adHeight);if(null===b)return this._isNeededBeacon=!1,null;var d=this.ssp.compass.altBannerPath,h=this.ssp.compass.altBannerClickUrl,d=""+('<a href="'+h+'" target="_blank" border="0" style="border:0">')+('<img src="'+d+b+'" border="0" style="border:0">'),
d=d+"</a>";this._isNeededBeacon=!1}this._adTag=0<d.length?d:this._adTag;this._adTag='<html><body style="margin:0;padding:0;border:0;">'+this._adTag+"</body></html>"}else a=this._iframe.contentDocument,d+='<meta name="viewport" content="width='+b+', user-scalable=no">',d+='<body style="text-align: center">',d+=this._adTag,this._adTag=d+="</body>";return a};b.prototype.display=function(){if(this._adTag){var a=this._getIframeDocument(navigator.userAgent);null!==a&&(a.open(),a.write(this._adTag),a.close(),
this._appendBeacons())}};b.prototype._appendElement=function(a,b){if(b){var d=document.createElement("div");a.appendChild(d);d.outerHTML=b}};b.prototype._appendBeacons=function(){this._isNeededBeacon&&(this._appendElement(this._spotDivElement,this._impTag),this._appendElement(this._spotDivElement,this._syncTag))};return b}();
microadCompass.OverlayCreative=microadCompass.OverlayCreative||function(){function b(a,b){microadCompass.IframeCreative.apply(this,arguments);this._device=microadCompass.DeviceFactory.getInstance(navigator.userAgent)}b.prototype=microadCompass.Object.create(microadCompass.IframeCreative.prototype);b.prototype.constructor=b;b.DEFAULT_TIMEOUT=500;b.HIDE_OVERLAY=!1;b.prototype._pageRatio=1;b.prototype.initialize=function(){microadCompass.IframeCreative.prototype.initialize.apply(this);"0"===this._adWidth&&
this._calculateIframeSize();var a=-1*("0"===this._adWidth?this._iframe.width.replace("px",""):this._adWidth)/2;this._spotDivElement.style.position="fixed";this._spotDivElement.style.bottom="0";this._spotDivElement.style.left="50%";this._spotDivElement.style.marginLeft=a+"px";this._spotDivElement.style.zIndex=2999999;this._spotDivElement.style.height=this._adHeight/this._pageRatio+"px";var b=this;setInterval(function(){b._adjustAdPosition()},100)};b.prototype.display=function(){microadCompass.IframeCreative.prototype.display.apply(this);
this._adjustAdPosition();this._showAd()};b.prototype._showAd=function(){this._spotDivElement.style.display="-moz-box";this._spotDivElement.style.display="-webkit-box"};b.prototype._adjustAdPosition=function(){this._calculatePosition();"top"===this._overlayPosition?(this._spotDivElement.style.bottom="",this._spotDivElement.style.top=this._getTopValue()+"px"):(this._spotDivElement.style.top="",this._spotDivElement.style.bottom="0px")};b.prototype._changeOpacity=function(a){a.opacity=0;var b=setInterval(function(){1>
1*a.opacity?a.opacity=1*a.opacity+.1:(a.opacity=1,clearInterval(b),b=null)},25)};b.prototype._getTopValue=function(){return this._top};b.prototype._calculatePosition=function(){var a=0;this._oldOverlayPosition=this._overlayPosition;this._isScrollDisabledPage()||this._isNotScrollToBottom()||this._oldConditions()?(this._overlayPosition="bottom",a=(window.innerHeight-this._adHeight)/this._pageRatio):this._overlayPosition="top";this._oldOverlayPosition!=this._overlayPosition&&this._changeOpacity(this._spotDivElement.style);
this._top=a};b.prototype._isScrollDisabledPage=function(){return window.innerHeight===this._getScreenHeight()};b.prototype._isNotScrollToBottom=function(){return window.pageYOffset+window.innerHeight+1<this._getScreenHeight()};b.prototype._oldConditions=function(){return window.pageYOffset*this._pageRatio<this._adHeight};b.prototype._getScreenHeight=function(){return Math.max.apply(null,[document.body.clientHeight,document.body.scrollHeight,document.documentElement.scrollHeight,document.documentElement.clientHeight])};
return b}();microadCompass.DeviceFactory=microadCompass.DeviceFactory||function(){function b(){throw new ReferenceError("[MicroAd COMPASS] Do not construct this object");}b.getInstance=function(a){return/(iphone|ipad|ipod)/i.test(a)?new microadCompass.IosDevice(a):/android/i.test(a)?new microadCompass.AndroidDevice(a):new microadCompass.SmartDevice(a)};return b}();
microadCompass.SmartDevice=microadCompass.SmartDevice||function(){function b(a){this.userAgent=a}function a(){return/windows phone/i.test(navigator.userAgent)}b.prototype.orientationChange="orientationchange";b.prototype.touchstart=a()?"MSPointerDown":"touchstart";b.prototype.touchmove=a()?"MSPointerMove":"touchmove";b.prototype.touchend=a()?"MSPointerUp":"touchend";return b}();
microadCompass.IosDevice=microadCompass.IosDevice||function(){function b(a){this.userAgent=a}b.prototype.orientationChange="orientationchange";b.prototype.touchstart="touchstart";b.prototype.touchmove="touchmove";b.prototype.touchend="touchend";return b}();
microadCompass.AndroidDevice=microadCompass.AndroidDevice||function(){function b(a){this.userAgent=a;this.orientationChange=this._getOrientationChangeName()}b.prototype.touchstart="mousedown";b.prototype.touchmove="mousemove";b.prototype.touchend="mouseup";b.prototype._getOrientationChangeName=function(){var a=this.userAgent.match(/Android[^;]*/)[0].split(/[\s\.-]/),b=a[1],a=a[2];return 2<b||2==b&&1<a?"orientationchange":"resize"};return b}();
microadCompass.AdCode=microadCompass.AdCode||function(){function b(){}b.prototype.convertAdCodeLessThanIE9=function(a){var b="";a=a.replace("\r\n","\n");a=a.split("\n");for(var d=0;d<a.length;d++)if(0<=a[d].indexOf("adingoFluct.showAd")){var h=!1;window.attachEvent?(b+="window.attachEvent('onload', function(){\n",h=!0):window.addEventListener&&(b+="window.addEventListener('load', function(){\n",h=!0);b+=a[d]+"\n";h&&(b+="});\n")}else b+=a[d]+"\n";return b};return b}();
microadCompass.SSP=microadCompass.SSP||function(){return function(){this.fluct=new microad.advertising.ssp.Fluct;this.compass=new microad.advertising.ssp.Compass}}();
microad.advertising.ssp.Compass=microad.advertising.ssp.Compass=function(){return function(){var b=new microadCompass.Settings(microadCompass.environment);this.altBannerPath="http:"+{jp:"//i.microad.net/images/compass/",apac:"//i.microad.net/images/compass_en/"}[b.deliveryArea];this.altBannerClickUrl="http:"+{jp:"//www.microad.co.jp/service/compass/",apac:"//www.microad.co.jp/en/service/compass/"}[b.deliveryArea];this.altBanners="728-90 468-60 336-280 300-600 300-250 260-230 200-200 160-600".split(" ")}}();
microad.advertising.ssp.Fluct=microad.advertising.ssp.Fluct=function(){function b(){}b.prototype=microadCompass.Object.create(microadCompass.AdCode.prototype);return b.prototype.constructor=b}();
microadCompass.Cookie=microadCompass.Cookie||function(){function b(b){if(a)return a;a=this;this._settings=b;return a}var a;b.prototype.cookieEnabledFlag=!1;b.prototype.beginGetCookieEnabledFlag=function(b){this._getCookieEnabledCallback=b;this.iframeElement=this.createIframe();null===document.body?(b=document.getElementsByTagName("script")[0],b.parentNode.insertBefore(this.iframeElement,b)):document.body.appendChild(this.iframeElement);this.iframeElement.src=this._settings.cookieEnabledGetUrl;window.addEventListener?
window.addEventListener("message",function(b){if(b.origin===a._settings.cacheUrl)a.oneTimeCallback(b)},!1):window.attachEvent&&window.attachEvent("onmessage",function(b){if(b.origin===a._settings.cacheUrl)a.oneTimeCallback(b)})};b.prototype.createIframe=function(){var a=document.createElement("iframe");a.width=1;a.height=1;a.frameborder=0;a.setAttribute("style","position:absolute; top:-9999px; left: -9999px; border-style: none");return a};b.prototype.oneTimeCallback=function(b){b.hasOwnProperty&&
b.hasOwnProperty("source")?b.source===a.iframeElement.contentWindow&&(a.cookieEnabledFlag=!!b.data,microadCompass.cookieEnabled=a.cookieEnabledFlag):a.cookieEnabledFlag=!!b.data;a._getCookieEnabledCallback&&a._getCookieEnabledCallback(a.cookieEnabledFlag);window.removeEventListener?window.removeEventListener("message",a.oneTimeCallback,!1):window.detachEvent&&window.detachEvent("onmessage",a.oneTimeCallback)};return b}();
microadCompass.Flash=microadCompass.Flash||function(){function b(){}b.isEnabled=function(){if(navigator.mimeTypes["application/x-shockwave-flash"])return!0;try{if(new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))return!0}catch(a){return!1}};b.getVersion=function(){if(!b.isEnabled())return null;if(navigator.plugins&&navigator.mimeTypes["application/x-shockwave-flash"]){var a=navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin;if(a)return parseInt(a.description.match(/\d+\.\d+/));a=
navigator.plugins["Shockwave Flash"];return void 0===a?null:a.version}try{a=(new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")).GetVariable("$version").match(/([0-9]+)/)}catch(c){try{a=(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version").match(/([0-9]+)/)}catch(d){}}if(a)return parseInt(a[0])};return b}();
microadCompass.QueueProcessor=microadCompass.QueueProcessor||function(){function b(a,b,d,h,l){if("undefined"===typeof b)throw new TypeError('[MicroAd COMPASS] "queueArray" is necessary to construct QueueProcessor.');if("undefined"===typeof d)throw new TypeError('[MicroAd COMPASS] "cookieEnabledFlag" is necessary to construct QueueProcessor.');if("undefined"===typeof h)throw new TypeError('[MicroAd COMPASS] "flashEnabledFlag" is necessary to construct QueueProcessor.');this._settings=a;this._queue=
b;this._prefetchedParams.cookieEnabledFlag=d;this._prefetchedParams.flashEnabledFlag=h;this._prefetchedParams.flashVersion=l}b.prototype._prefetchedParams={};b.prototype.appendHook=function(){this._originalPush=this._queue.push;this._queue.push=this._proxyEnqueueToProcessQueue};b.prototype.removeHook=function(){this._queue.push=this._originalPush};b.prototype._proxyEnqueueToProcessQueue=function(a){if(this._processQueue)this._processQueue(a);else{var b=new microadCompass.Settings(microadCompass.environment);
(new microadCompass.QueueProcessor(b,microadCompass.queue,microadCompass.cookieEnabled,microadCompass.Flash.isEnabled(),microadCompass.Flash.getVersion()))._processQueue(a)}};b.prototype._dequeue=function(){return 0<this._queue.length?this._queue.shift():null};b.prototype.processBulkQueue=function(){for(var a=this._queue.length,b=0;b<a;b++){var d=this._dequeue();this._processQueue(d)}};b.prototype._processQueue=function(a){(new microadCompass.AdRequestor(this._settings)).sendRequest(a,this._prefetchedParams.cookieEnabledFlag,
this._prefetchedParams.flashEnabledFlag,this._prefetchedParams.flashVersion)};return b}();
microadCompass.Settings=microadCompass.Settings||function(){var b={production:"s-rtb.send.microad.jp/ad",staging:"",development:""},a={production:"cache.send.microad.jp/js/cookie_enabled_get.html",staging:"",development:""},c={production:"cache.send.microad.jp",staging:"",development:""},d={production:"deb.send.microad.jp/",staging:"",development:""};return function(h){this.env=h;h=document.location.protocol;this.serverUrl=("https:"===h?"https://":"http://")+b[this.env];this.cookieEnabledGetUrl=("https:"===
h?"https://":"http://")+a[this.env];this.cacheUrl=("https:"===h?"https://":"http://")+c[this.env];this.debugUrl=("https:"===h?"https://":"http://")+d[this.env];this.deliveryArea="jp"}}();microadCompass.legacyIE&&(new microadCompass.AdInitializer).initialize();
